name: Make sure new PRs are sent to development

on:
    pull_request_target: # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ before using
        types: [opened, edited]

jobs:
    check-branch:
        name: Check PR Branch
        runs-on: ubuntu-latest
        steps:
            - uses: Vankka/pr-target-branch-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  target: master
                  exclude: development # Don't prevent going from branch: development -> master
                  change-to: development
                  comment: |
                      Your PR was set to target `master`, PRs should be set to target `development`
                      The base branch of this PR has been automatically changed to `development`, please check that there are no merge conflicts
                  already-exists-action: close_other_continue
                  already-exists-comment: 'Closing {url} as it has the same base branch'
                  already-exists-other-comment: 'This PR was closed in favor of {url}'
